# coding: utf-8

# flake8: noqa

"""
    Lance Catalog REST Specification

    **Lance Catalog** is an OpenAPI specification on top of the storage-based Lance format. It provides an integration point for catalog service like Apache Hive MetaStore (HMS), Apache Gravitino, etc. to store and use Lance tables. To integrate, the catalog service implements a **Lance Catalog Adapter**, which is a REST server that converts the Lance catalog requests to native requests against the catalog service. Different tools can integrate with Lance Catalog using the generated OpenAPI clients in various languages, and invoke operations in Lance Catalog to read, write and manage Lance tables in the integrated catalog services. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.1"

# import apis into sdk package
from lance_catalog_urllib3_client.api.namespace_api import NamespaceApi
from lance_catalog_urllib3_client.api.table_api import TableApi

# import ApiClient
from lance_catalog_urllib3_client.api_response import ApiResponse
from lance_catalog_urllib3_client.api_client import ApiClient
from lance_catalog_urllib3_client.configuration import Configuration
from lance_catalog_urllib3_client.exceptions import OpenApiException
from lance_catalog_urllib3_client.exceptions import ApiTypeError
from lance_catalog_urllib3_client.exceptions import ApiValueError
from lance_catalog_urllib3_client.exceptions import ApiKeyError
from lance_catalog_urllib3_client.exceptions import ApiAttributeError
from lance_catalog_urllib3_client.exceptions import ApiException

# import models into sdk package
from lance_catalog_urllib3_client.models.create_namespace_request import CreateNamespaceRequest
from lance_catalog_urllib3_client.models.create_namespace_response import CreateNamespaceResponse
from lance_catalog_urllib3_client.models.error_response import ErrorResponse
from lance_catalog_urllib3_client.models.get_namespace_response import GetNamespaceResponse
from lance_catalog_urllib3_client.models.get_table_response import GetTableResponse
from lance_catalog_urllib3_client.models.list_namespaces_response import ListNamespacesResponse
from lance_catalog_urllib3_client.models.register_table_request import RegisterTableRequest
