# coding: utf-8

"""
    Lance Catalog REST Specification

    **Lance Catalog** is an OpenAPI specification on top of the storage-based Lance format. It provides an integration point for catalog service like Apache Hive MetaStore (HMS), Apache Gravitino, etc. to store and use Lance tables. To integrate, the catalog service implements a **Lance Catalog Adapter**, which is a REST server that converts the Lance catalog requests to native requests against the catalog service. Different tools can integrate with Lance Catalog using the generated OpenAPI clients in various languages, and invoke operations in Lance Catalog to read, write and manage Lance tables in the integrated catalog services. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_catalog_urllib3_client.models.create_namespace_request import CreateNamespaceRequest

class TestCreateNamespaceRequest(unittest.TestCase):
    """CreateNamespaceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNamespaceRequest:
        """Test CreateNamespaceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateNamespaceRequest`
        """
        model = CreateNamespaceRequest()
        if include_optional:
            return CreateNamespaceRequest(
                name = '',
                mode = 'CREATE',
                options = {
                    'key' : ''
                    }
            )
        else:
            return CreateNamespaceRequest(
                name = '',
                mode = 'CREATE',
        )
        """

    def testCreateNamespaceRequest(self):
        """Test CreateNamespaceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
