# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VERSION = 0.0.1

clean-java-apache-client:
	rm -rf lance-catalog-apache-client

gen-java-apache-client: clean-java-apache-client
	openapi-generator-cli generate \
	  -i ../spec/catalog.yaml \
	  -g java \
	  -o lance-catalog-apache-client \
	  --ignore-file-override=.apache-client-ignore \
	  --additional-properties=groupId=com.lancedb,artifactId=lance-catalog-apache-client,artifactVersion=$(VERSION),parentGroupId=com.lancedb,parentArtifactId=lance-catalog-root,parentVersion=$(VERSION),parentRelativePath=pom.xml,library=apache-httpclient,apiPackage=com.lancedb.lance.catalog.client.apache.api,modelPackage=com.lancedb.lance.catalog.client.apache.model,hideGenerationTimestamp=true,licenseName=Apache-2.0,licenseUrl=https://www.apache.org/licenses/LICENSE-2.0.txt
	sed -i -e 's#<junit-version>5.10.2</junit-version>#<junit-version>5.8.2</junit-version>#g' lance-catalog-apache-client/pom.xml
	rm -f lance-catalog-apache-client/pom.xml-e

lint-java-apache-client: gen-java-apache-client gen-java-springboot-server
	./mvnw spotless:apply -pl lance-catalog-apache-client -am

build-java-apache-client: gen-java-apache-client lint-java-apache-client
	./mvnw install -pl lance-catalog-apache-client -am

clean-java-springboot-server:
	rm -rf lance-catalog-springboot-server

gen-java-springboot-server: clean-java-springboot-server
	openapi-generator-cli generate \
	  -i ../spec/catalog.yaml \
	  -g spring \
      -o lance-catalog-springboot-server \
      --additional-properties=groupId=com.lancedb,artifactId=lance-catalog-springboot-server,artifactVersion=$(VERSION),parentGroupId=com.lancedb,parentArtifactId=lance-catalog-root,parentVersion=$(VERSION),parentRelativePath=pom.xml,library=spring-boot,interfaceOnly=true,useOptional=true,openApiNullable=false,java8=true,apiPackage=com.lancedb.lance.catalog.server.springboot.api,modelPackage=com.lancedb.lance.catalog.server.springboot.model,useTags=true,skipDefaultInterface=false,hideGenerationTimestamp=true,licenseName=Apache-2.0,licenseUrl=https://www.apache.org/licenses/LICENSE-2.0.txt

lint-java-springboot-server: gen-java-apache-client gen-java-springboot-server
	./mvnw spotless:apply -pl lance-catalog-springboot-server -am

build-java-springboot-server: gen-java-springboot-server lint-java-springboot-server
	./mvnw install -pl lance-catalog-springboot-server -am

clean: clean-java-apache-client clean-java-springboot-server

gen: gen-java-apache-client gen-java-springboot-server lint-java-apache-client lint-java-springboot-server

build: build-java-apache-client build-java-springboot-server