# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
openapi: 3.1.1
info:
  title: Lance Catalog REST Specification
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
  description: |
    **Lance Catalog** is an OpenAPI specification on top of the storage-based Lance format.
    It provides an integration point for catalog service like Apache Hive MetaStore (HMS), Apache Gravitino, etc.
    to store and use Lance tables. To integrate, the catalog service implements a **Lance Catalog Adapter**,
    which is a REST server that converts the Lance catalog requests to native requests against the catalog service.
    Different tools can integrate with Lance Catalog using the generated OpenAPI clients in various languages,
    and invoke operations in Lance Catalog to read, write and manage Lance tables in the integrated catalog services.

servers:
  - url: "{scheme}://{host}:{port}/{basePath}"
    description: Generic server URL with all parts configurable
    variables:
      scheme:
        default: http
      host:
        default: localhost
      port:
        default: "2333"
      basePath:
        default: ""
  - url: "{scheme}://{host}/{basePath}"
    description: Server URL when the port can be inferred from the scheme
    variables:
      scheme:
        default: http
      host:
        default: localhost
      basePath:
        default: ""

security:
  - OAuth2: []
  - BearerAuth: []

paths:
  /v1/namespaces:
    post:
      tags: [ Namespace ]
      summary: >
        Create a new namespace. A catalog can manage one or more namespaces. A namespace is used to manage one or more tables.
        There are three modes when trying to create a namespace:
          * CREATE: Create the namespace if it does not exist. If a namespace of the same name already exists, the operation fails with 400.
          * EXIST_OK: Create the namespace if it does not exist. If a namespace of the same name already exists, the operation succeeds and the existing namespace is kept.
          * OVERWRITE: Create the namespace if it does not exist. If a namespace of the same name already exists, the existing namespace is dropped and a new namespace with this name with no table is created.
      operationId: CreateNamespace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNamespaceRequest'
      responses:
        200:
          $ref: '#/components/responses/CreateNamespaceResponse'
        400:
          $ref: '#/components/responses/BadRequestErrorResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        406:
          $ref: '#/components/responses/UnsupportedOperationResponse'
        409:
          $ref: '#/components/responses/ConflictErrorResponse'
        503:
          $ref: '#/components/responses/ServiceUnavailableResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'

    get:
      tags: [ Namespace ]
      summary: >
        List all namespaces in the catalog.
      operationId: ListNamespaces
      parameters:
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
      responses:
        200:
          $ref: '#/components/responses/ListNamespacesResponse'
        400:
          $ref: '#/components/responses/BadRequestErrorResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        406:
          $ref: '#/components/responses/UnsupportedOperationResponse'
        503:
          $ref: '#/components/responses/ServiceUnavailableResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'

  /v1/namespaces/{ns}:
    parameters:
      - $ref: '#/components/parameters/namespace'

    get:
      tags: [ Namespace ]
      summary: Get information about a namespace
      operationId: GetNamespace
      description: Return a detailed information for a given namespace
      responses:
        200:
          $ref: '#/components/responses/GetNamespaceResponse'
        400:
          $ref: '#/components/responses/BadRequestErrorResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        503:
          $ref: '#/components/responses/ServiceUnavailableResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'

    delete:
      tags: [ Namespace ]
      summary: Drop a namespace from the catalog. Namespace must be empty.
      operationId: DropNamespace
      responses:
        204:
          description: Success, no content
        400:
          $ref: '#/components/responses/BadRequestErrorResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        409:
          $ref: '#/components/responses/ConflictErrorResponse'
        503:
          $ref: '#/components/responses/ServiceUnavailableResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'

    head:
      tags: [ Namespace ]
      summary: Check if a namespace exists
      operationId: NamespaceExists
      description:
        Check if a namespace exists. The response does not contain a body.
      responses:
        200:
          description: Success, no content
        400:
          $ref: '#/components/responses/BadRequestErrorResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        503:
          $ref: '#/components/responses/ServiceUnavailableResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'

  /v1/namespaces/{ns}/register:
    post:
      tags: [ Table ]
      summary: >
        Register a new table in the given namespace. A table represents a lance dataset. 
        In Lance catalog, a table must be hosted in a namespace.
      operationId: RegisterTable
      parameters:
        - $ref: '#/components/parameters/namespace'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterTableRequest'
      responses:
        200:
          $ref: '#/components/responses/GetTableResponse'
        400:
          $ref: '#/components/responses/BadRequestErrorResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        406:
          $ref: '#/components/responses/UnsupportedOperationResponse'
        409:
          $ref: '#/components/responses/ConflictErrorResponse'
        503:
          $ref: '#/components/responses/ServiceUnavailableResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'

  /v1/namespaces/{ns}/tables/{table}:
    parameters:
      - $ref: '#/components/parameters/namespace'
      - $ref: '#/components/parameters/table'

    get:
      tags: [ Table ]
      summary: Get a table from the catalog
      operationId: GetTable
      description:
        Get a table's detailed information under a specified namespace from the catalog.
      responses:
        200:
          $ref: '#/components/responses/GetTableResponse'
        400:
          $ref: '#/components/responses/BadRequestErrorResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        503:
          $ref: '#/components/responses/ServiceUnavailableResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'

components:
  parameters:
    namespace:
      name: ns
      in: path
      required: true
      description:
        The name of the namespace.
      schema:
        type: string

    pageToken:
      name: pageToken
      in: query
      required: false
      allowEmptyValue: true
      schema:
        $ref: '#/components/schemas/PageToken'

    pageSize:
      name: pageSize
      in: query
      description:
        An inclusive upper bound of the number of results that a client will receive.
      required: false
      schema:
        type: integer
        minimum: 1

    table:
      name: table
      in: path
      description:
        A table name.
      required: true
      schema:
        type: string

  schemas:
    ErrorModel:
      type: object
      description: JSON error model(based on [RFC-7807](https://datatracker.ietf.org/doc/html/rfc7807)) payload returned in a response with further details on the error
      required:
        - type
      properties:
        type:
          type: string
          description: a URI identifier that categorizes the error
          example: /errors/incorrect-user-pass
        title:
          type: string
          description: a brief, human-readable message about the error
          example: Incorrect username or password
        status:
          type: integer
          minimum: 400
          maximum: 600
          description: HTTP response code, (if present) it must match the actual HTTP code returned by the service
          example: 404
        detail:
          type: string
          description: a human-readable explanation of the error
          example: Authentication failed due to incorrect username or password
        instance:
          type: string
          description: a URI that identifies the specific occurrence of the error
          example: /login/log/abc123

    CreateNamespaceRequest:
      type: object
      required: [ name, mode ]
      properties:
        name: { type: string }
        mode:
          type: string
          enum: [ CREATE, EXIST_OK, OVERWRITE ]
        options:
          type: object
          additionalProperties: { type: string }

    CreateNamespaceResponse:
      type: object
      required:
        - name
      properties:
        name: { type: string }
        properties:
          type: object
          additionalProperties:
            type: string
          description:
            Properties stored on the namespace, if supported by the server.
          example: { "created_at": "1452120468" }
          default: { }

    ListNamespacesResponse:
      type: object
      required:
        - namespaces
      properties:
        namespaces:
          description: An array of namespace names in the catalog.
          type: array
          uniqueItems: true
          items:
            type: string
            example: "accounting"
        nextPageToken:
          $ref: "#/components/schemas/PageToken"

    GetNamespaceResponse:
      type: object
      required:
        - namespace
      properties:
        namespace:
          type: string
        properties:
          type: object
          description:
            Properties stored on the namespace, if supported by the server.
            If the server does not support namespace properties, it should return null for this field.
            If namespace properties are supported, but none are set, it should return an empty object.
          additionalProperties:
            type: string
          example: { "owner": "Ralph", 'created_at': '1452120468' }
          default: { }
          nullable: true

    PageToken:
      description:
        An opaque token that allows pagination for list APIs (e.g. ListNamespaces).
        
        For an initial client request for a list API, if the server cannot return all items in one response,
        or if there are more items than the `pageSize` specified in the client request,
        the server must return a `nextPageToken` in the response indicating there are more results available.
        
        After the initial request, the value of `nextPageToken` from each response must be used by the client 
        as the `pageToken` parameter value for the next request.
        
        Clients must interpret either `null`, missing value or empty string value of `nextPageToken` from 
        a server response as the end of the listing results.
      type: string
      nullable: true

    RegisterTableRequest:
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
        location:
          type: string

    GetTableResponse:
      description: |
        Result used when a table is successfully loaded.
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
        location:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string

  responses:
    CreateNamespaceResponse:
      description:
        Represents a successful call to create a namespace.
        Returns the namespace created, as well as any properties that were stored for the namespace,
        including those the server might have added. Implementations are not required to support namespace
        properties.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateNamespaceResponse'
          example: {
            "namespace": [ "lance.ns1" ],
            "properties": { "created_at": "1452120468" }
          }

    ListNamespacesResponse:
      description: A list of namespaces
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListNamespacesResponse'
          examples:
            NonEmptyResponse:
              $ref: '#/components/examples/ListNamespacesNonEmptyExample'
            EmptyResponse:
              $ref: '#/components/examples/ListNamespacesEmptyExample'

    GetNamespaceResponse:
      description:
        Returns a namespace, as well as any properties stored on the namespace if namespace properties
        are supported by the server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetNamespaceResponse'

    GetTableResponse:
      description: Table properties result when loading a table
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetTableResponse'

    BadRequestErrorResponse:
      description:
        Indicates a bad request error. It could be caused by an unexpected request
        body format or other forms of request validation failure, such as invalid json.
        Usually serves application/json content, although in some cases simple text/plain content might
        be returned by the server's middleware.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/bad-request",
            "title": "Malformed request",
            "status": 400,
            "detail": "",
            "instance": "/v1/namespaces"
          }

    UnauthorizedResponse:
      description: Unauthorized. The request lacks valid authentication credentials for the operation.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/unauthorized-request",
            "title": "No valid authentication credentials for the operation",
            "status": 401,
            "detail": "",
            "instance": "/v1/namespaces"
          }

    ForbiddenResponse:
      description: Forbidden. Authenticated user does not have the necessary permissions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/forbidden-request",
            "title": "Not authorized to make this request",
            "status": 403,
            "detail": "",
            "instance": "/v1/namespaces"
          }

    NotFoundResponse:
      description:
        A server-side problem that means can not find the specified resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/not-found-error",
            "title": "Not found Error",
            "status": 404,
            "detail": "",
            "instance": "/v1/namespaces/{ns}"
          }

    UnsupportedOperationResponse:
      description: Not Acceptable / Unsupported Operation. The server does not support this operation.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/unsupported-operation",
            "title": "The server does not support this operation",
            "status": 406,
            "detail": "",
            "instance": "/v1/namespaces"
          }

    ConflictErrorResponse:
      description: The request conflicts with the current state of the target resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/conflict",
            "title": "The namespace has been concurrently modified",
            "status": 409,
            "detail": "",
            "instance": "/v1/namespaces/{ns}"
          }

    ServiceUnavailableResponse:
      description:
        The service is not ready to handle the request. The client should wait and retry.
        The service may additionally send a Retry-After header to indicate when to retry.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/service-unavailable",
            "title": "Slow down",
            "status": 503,
            "detail": "",
            "instance": "/v1/namespaces"
          }

    ServerErrorResponse:
      description:
        A server-side problem that might not be addressable from the client
        side. Used for server 5xx errors without more specific documentation in
        individual routes.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          example: {
            "type": "/errors/server-error",
            "title": "Internal Server Error",
            "status": 500,
            "detail": "",
            "instance": "/v1/namespaces"
          }

  examples:
    ListNamespacesEmptyExample:
      summary: An empty list of namespaces
      value: {
        "namespaces": [ ]
      }

    ListNamespacesNonEmptyExample:
      summary: A non-empty list of namespaces
      value: {
        "namespaces": [
          "accounting",
          "credits"
        ]
      }
