/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lancedb.github.io/lance-namespace/spec/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lancedb.github.io/lance-namespace/spec/impls/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlterTransactionRequest : Alter a transaction with a list of actions. The server should either succeed and apply all actions, or fail and apply no action. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlterTransactionRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "actions")]
    pub actions: Vec<models::AlterTransactionAction>,
}

impl AlterTransactionRequest {
    /// Alter a transaction with a list of actions. The server should either succeed and apply all actions, or fail and apply no action. 
    pub fn new(id: String, actions: Vec<models::AlterTransactionAction>) -> AlterTransactionRequest {
        AlterTransactionRequest {
            id,
            actions,
        }
    }
}

