/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lancedb.github.io/lance-namespace/spec/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lancedb.github.io/lance-namespace/spec/impls/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteFromTableRequest {
    /// The table name
    #[serde(rename = "name")]
    pub name: String,
    /// The namespace identifier
    #[serde(rename = "namespace")]
    pub namespace: Vec<String>,
    /// SQL predicate to filter rows for deletion
    #[serde(rename = "predicate")]
    pub predicate: String,
}

impl DeleteFromTableRequest {
    pub fn new(name: String, namespace: Vec<String>, predicate: String) -> DeleteFromTableRequest {
        DeleteFromTableRequest {
            name,
            namespace,
            predicate,
        }
    }
}

