/*
 * Lance REST Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts: The `components/schemas`, `components/responses`, `components/examples` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lancedb.github.io/lance-namespace/spec/operations for more details. The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lancedb.github.io/lance-namespace/spec/impls/rest for more details. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexListResponse {
    /// The table name
    #[serde(rename = "name")]
    pub name: String,
    /// The namespace identifier
    #[serde(rename = "namespace")]
    pub namespace: Vec<String>,
    /// Table location (usually empty)
    #[serde(rename = "location")]
    pub location: String,
    /// Additional properties (usually empty)
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    /// List of indexes on the table
    #[serde(rename = "indexes")]
    pub indexes: Vec<models::IndexListItemResponse>,
}

impl IndexListResponse {
    pub fn new(name: String, namespace: Vec<String>, location: String, indexes: Vec<models::IndexListItemResponse>) -> IndexListResponse {
        IndexListResponse {
            name,
            namespace,
            location,
            properties: None,
            indexes,
        }
    }
}

