/*
 * Lance REST Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts: The `components/schemas`, `components/responses`, `components/examples` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lancedb.github.io/lance-namespace/spec/operations for more details. The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lancedb.github.io/lance-namespace/spec/impls/rest for more details. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace")]
    pub namespace: Vec<String>,
    /// Query vector for similarity search
    #[serde(rename = "vector")]
    pub vector: Vec<f32>,
    /// Number of results to return
    #[serde(rename = "k")]
    pub k: i32,
    /// Optional SQL filter expression
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    /// Optional list of columns to return
    #[serde(rename = "columns", skip_serializing_if = "Option::is_none")]
    pub columns: Option<Vec<String>>,
    /// Distance metric to use
    #[serde(rename = "distance_type", skip_serializing_if = "Option::is_none")]
    pub distance_type: Option<DistanceType>,
    /// Whether to apply filtering before vector search
    #[serde(rename = "prefilter", skip_serializing_if = "Option::is_none")]
    pub prefilter: Option<bool>,
    /// Whether to bypass vector index
    #[serde(rename = "bypass_vector_index", skip_serializing_if = "Option::is_none")]
    pub bypass_vector_index: Option<bool>,
    /// Search effort parameter for HNSW index
    #[serde(rename = "ef", skip_serializing_if = "Option::is_none")]
    pub ef: Option<i32>,
    /// Number of probes for IVF index
    #[serde(rename = "nprobes", skip_serializing_if = "Option::is_none")]
    pub nprobes: Option<i32>,
    /// Refine factor for search
    #[serde(rename = "refine_factor", skip_serializing_if = "Option::is_none")]
    pub refine_factor: Option<i32>,
    /// Whether to include row ID in results
    #[serde(rename = "with_row_id", skip_serializing_if = "Option::is_none")]
    pub with_row_id: Option<bool>,
    /// Number of results to skip
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Table version to query
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

impl QueryRequest {
    pub fn new(name: String, namespace: Vec<String>, vector: Vec<f32>, k: i32) -> QueryRequest {
        QueryRequest {
            name,
            namespace,
            vector,
            k,
            filter: None,
            columns: None,
            distance_type: None,
            prefilter: None,
            bypass_vector_index: None,
            ef: None,
            nprobes: None,
            refine_factor: None,
            with_row_id: None,
            offset: None,
            version: None,
        }
    }
}
/// Distance metric to use
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DistanceType {
    #[serde(rename = "l2")]
    L2,
    #[serde(rename = "cosine")]
    Cosine,
    #[serde(rename = "dot")]
    Dot,
}

impl Default for DistanceType {
    fn default() -> DistanceType {
        Self::L2
    }
}

