# coding: utf-8

"""
    Lance REST Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts: The `components/schemas`, `components/responses`, `components/examples` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lancedb.github.io/lance-namespace/spec/operations for more details. The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lancedb.github.io/lance-namespace/spec/impls/rest for more details. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.create_index_request import CreateIndexRequest

class TestCreateIndexRequest(unittest.TestCase):
    """CreateIndexRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIndexRequest:
        """Test CreateIndexRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIndexRequest`
        """
        model = CreateIndexRequest()
        if include_optional:
            return CreateIndexRequest(
                name = '',
                namespace = [
                    ''
                    ],
                column = '',
                index_type = 'BTREE',
                metric_type = 'l2',
                with_position = True,
                base_tokenizer = '',
                language = '',
                max_token_length = 0,
                lower_case = True,
                stem = True,
                remove_stop_words = True,
                ascii_folding = True
            )
        else:
            return CreateIndexRequest(
                name = '',
                namespace = [
                    ''
                    ],
                column = '',
                index_type = 'BTREE',
        )
        """

    def testCreateIndexRequest(self):
        """Test CreateIndexRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
