# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lancedb.github.io/lance-namespace/spec/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lancedb.github.io/lance-namespace/spec/impls/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.api.transaction_api import TransactionApi


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionApi()

    def tearDown(self) -> None:
        pass

    def test_alter_transaction(self) -> None:
        """Test case for alter_transaction

        Alter information of a transaction.
        """
        pass

    def test_describe_transaction(self) -> None:
        """Test case for describe_transaction

        Describe information about a transaction
        """
        pass


if __name__ == '__main__':
    unittest.main()
